# Generated by Django 5.0.3 on 2025-04-16 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_administrador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('especialidad', models.CharField(max_length=100)),
                ('membresia', models.CharField(choices=[('Competitor', 'Competitor'), ('Pro Athlete', 'Pro Athlete')], max_length=20)),
                ('cotizacion', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fecha_disponible', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('horario', models.DateTimeField()),
                ('cupos_maximos', models.PositiveIntegerField()),
                ('cupos_disponibles', models.PositiveIntegerField()),
                ('membresia', models.CharField(choices=[('Competitor', 'Competitor'), ('Pro Athlete', 'Pro Athlete')], max_length=20)),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='main_app.entrenador')),
            ],
        ),
    ]
