# Generated by Django 5.0.3 on 2025-04-16 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_entrenador_clase'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenador',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='entrenadores/'),
        ),
    ]
