# Generated by Django 5.0.3 on 2025-04-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_entrenador_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenador',
            name='hora_disponible_desde',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AddField(
            model_name='entrenador',
            name='hora_disponible_hasta',
            field=models.TimeField(default='21:00'),
        ),
    ]
