# Generated by Django 5.0.3 on 2025-04-25 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_membresia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.clase')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.cliente')),
            ],
        ),
    ]
