# Generated by Django 5.0.3 on 2025-04-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_inscripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrenador',
            name='cotizacion',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=10),
        ),
    ]
